import type { saveImage } from './saveImage';

import { getDatabaseVersion } from 'database/utils';
import { adapterV1, getImage as getImageByHash } from 'database';

/**
 * Retrieve a Blob from the image object store.
 *
 * @param hash - The key where the image is stored, as generated by {@linkcode saveImage}
 *
 * @returns A Promise that resolves to a Blob containing image data,
 * if an image existed. Otherwise it resolves to null.
 *
 * @see {@linkcode saveImage} For how to save an image for retrieval.
 */
export async function getImage(hash: string): Promise<Blob | null> {
	// TODO: Get rid of this database v1 handling
	const dbVersion = await getDatabaseVersion();
	if (dbVersion === 1 || dbVersion === null) {
		return adapterV1.getImage(hash);
	}

	return (await getImageByHash(hash))?.file ?? null;
}
