// Type-only import to expose symbol in JSDoc
import { getDatabase, getIdbRequestPromise } from 'utils/indexedDB';
import type { saveImage } from './saveImage';

import { ObjectStoreName, doDatabaseTransaction } from 'utils';
import { IndexName } from 'data/shared/IndexName';
import type { DatabaseData } from 'data/shared/types';

/**
 * Retrieve a Blob from the image object store.
 *
 * @param key - The key where the image is stored, as generated by {@linkcode saveImage}
 *
 * @returns A Promise that resolves to a Blob containing image data,
 * if an image existed. Otherwise it resolves to null.
 *
 * @see {@linkcode saveImage} For how to save an image for retrieval.
 */
export async function getImage(key: string): Promise<Blob | null> {
	const db = await getDatabase();
	const transaction = db.transaction(ObjectStoreName.IMAGE);
	const imageOS = transaction.objectStore(ObjectStoreName.IMAGE);
	const imagesByHash = imageOS.index(IndexName.IMAGE_HASH);

	// TODO: Find a way to do this with type safety
	const image = await getIdbRequestPromise(
		imagesByHash.get(key) as IDBRequest<DatabaseData['image'][number]>
	);

	return image.file;
}
