import type { Status } from '../types';

import { ObjectStoreName } from '../metadata';
import { getStatusesInternal } from '../internal';

import { requestTransaction } from './requestTransaction';

/**
 * A cache of any `Promise` generated by a request to get all statuses, reused across all requests because statuses in the database are never modified.
 */
let promise: Promise<Status[]> | null = null;

/**
 * Loads data from all statuses. Will only ever request status data once, any subsequent requests will return the same result.
 */
export async function loadAllStatuses(): Promise<Status[]> {
	if (promise) {
		return promise;
	}

	promise = loadAllStatusesInternal();

	return promise;
}

/**
 * Loads data from all statuses.
 */
async function loadAllStatusesInternal(): Promise<Status[]> {
	const transaction = await requestTransaction([ObjectStoreName.STATUS], 'readonly');

	const statuses = await getStatusesInternal(transaction);

	return statuses;
}
