name: build-and-deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install and build
        run: |
          npm ci
          npm run build
        env:
          MODE: production

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'build'
          path: './'

  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: 'build'

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Test
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    needs: [build, test]
    if: github.ref == 'refs/heads/main'

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: 'build'

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './app'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
